(function initTransLensLanguages(root) {
  const SUPPORTED_LANGUAGES = Object.freeze([
    { code: 'ar', name: '阿拉伯语', englishName: 'Arabic' },
    { code: 'bg', name: '保加利亚语', englishName: 'Bulgarian' },
    { code: 'bn', name: '孟加拉语', englishName: 'Bengali' },
    { code: 'cs', name: '捷克语', englishName: 'Czech' },
    { code: 'da', name: '丹麦语', englishName: 'Danish' },
    { code: 'de', name: '德语', englishName: 'German' },
    { code: 'el', name: '希腊语', englishName: 'Greek' },
    { code: 'en', name: '英语', englishName: 'English' },
    { code: 'es', name: '西班牙语', englishName: 'Spanish' },
    { code: 'fi', name: '芬兰语', englishName: 'Finnish' },
    { code: 'fr', name: '法语', englishName: 'French' },
    { code: 'he', name: '希伯来语', englishName: 'Hebrew' },
    { code: 'hi', name: '印地语', englishName: 'Hindi' },
    { code: 'hr', name: '克罗地亚语', englishName: 'Croatian' },
    { code: 'hu', name: '匈牙利语', englishName: 'Hungarian' },
    { code: 'id', name: '印度尼西亚语', englishName: 'Indonesian' },
    { code: 'it', name: '意大利语', englishName: 'Italian' },
    { code: 'ja', name: '日语', englishName: 'Japanese' },
    { code: 'kn', name: '卡纳达语', englishName: 'Kannada' },
    { code: 'ko', name: '韩语', englishName: 'Korean' },
    { code: 'lt', name: '立陶宛语', englishName: 'Lithuanian' },
    { code: 'mr', name: '马拉地语', englishName: 'Marathi' },
    { code: 'nl', name: '荷兰语', englishName: 'Dutch' },
    { code: 'no', name: '挪威语', englishName: 'Norwegian' },
    { code: 'pl', name: '波兰语', englishName: 'Polish' },
    { code: 'pt', name: '葡萄牙语', englishName: 'Portuguese' },
    { code: 'ro', name: '罗马尼亚语', englishName: 'Romanian' },
    { code: 'ru', name: '俄语', englishName: 'Russian' },
    { code: 'sk', name: '斯洛伐克语', englishName: 'Slovak' },
    { code: 'sl', name: '斯洛文尼亚语', englishName: 'Slovenian' },
    { code: 'sv', name: '瑞典语', englishName: 'Swedish' },
    { code: 'ta', name: '泰米尔语', englishName: 'Tamil' },
    { code: 'te', name: '泰卢固语', englishName: 'Telugu' },
    { code: 'th', name: '泰语', englishName: 'Thai' },
    { code: 'tr', name: '土耳其语', englishName: 'Turkish' },
    { code: 'uk', name: '乌克兰语', englishName: 'Ukrainian' },
    { code: 'vi', name: '越南语', englishName: 'Vietnamese' },
    { code: 'zh', name: '简体中文', englishName: 'Chinese' },
    { code: 'zh-Hant', name: '繁体中文', englishName: 'Chinese (Traditional)' }
  ]);

  root.TransLensLanguages = { SUPPORTED_LANGUAGES };
})(typeof globalThis !== 'undefined' ? globalThis : self);
